# https://taskfile.dev

version: '3'

vars:
  COMPILER_OPTIONS: " -v" 

tasks:
  example:
    cmds:
      - python src/gpc.py -i examples/new_program.gpc -o build/output.bin {{.COMPILER_OPTIONS}}
    silent: true

  build: &build
    os: darwin
    cmds: 
    - |
        bash -c '
        mkdir -p build
        source .venv/bin/activate
        python src/gpc.py -i {{.INPUT}} -o {{.OUTPUT}} {{.COMPILER_OPTIONS}}
        '
    silent: true
    internal: true

  build: &build
    os: windows
    cmds: 
      - New-Item -Path . -Name "build" -ItemType Directory 
    silent: true
    internal: true

  all:
    deps: [board_01, board_02]
    cmds:
      - echo "Done building the applications"

  board_01:
    <<: *build
    vars: { INPUT: programma/board_01.gpc, OUTPUT: build/board_01.bin }
    cmds:
      - python src/gpc.py -i {{.INPUT}} -o {{.OUTPUT}} {{.COMPILER_OPTIONS}}
    internal: false

  board_02:
    <<: *build
    vars: { INPUT: programma/board_02.gpc, OUTPUT: build/board_02.bin }
    internal: false
